import { COALESCING_REDIS_CLIENT, ICoalescingService } from '@common/coalescing/coalescing.interface';
import { Inject, Injectable, OnModuleDestroy, OnModuleInit } from '@nestjs/common';
import { EventEmitter } from 'events';
import Redis from 'ioredis';

const LOCK_TTL_MS = 5000;

type CoalescingPayload<T> =
  | {
    ok: true;
    data: T;
  }
  | {
    ok: false;
    error: string;
  };

/**
 * Autogenerated: Distributed coalescing via Redis SET NX lock + Pub/Sub notification.
 *
 * Uses a single persistent subscriber connection + a Node.js EventEmitter
 * to fan out notifications in-process. This avoids the O(N) Redis connection
 * cost of the duplicate()-per-waiter approach.
 *
 * Fixes applied vs. naive single-connection approach:
 *
 *   1. Ref-counted channel subscriptions — only the last waiter to leave a
 *      channel actually unsubscribes from Redis, preventing early teardown
 *      that would silently drop messages for concurrent waiters on the same key.
 *
 *   2. Post-subscribe early-result check — after subscribing, we immediately
 *      read resultKey from Redis to handle the race where the lock-holder
 *      publishes 'done' before we finish subscribing.
 *
 *   3. Per-waiter timeout — prevents indefinite hangs when the lock-holder
 *      crashes before publishing.
 *
 *   4. No async in Promise constructor — subscribe is awaited before the
 *      Promise is created, so errors propagate correctly to the caller.
 */
@Injectable()
export class RedisPubSubCoalescingService
implements ICoalescingService, OnModuleInit, OnModuleDestroy
{
  private readonly emitter = new EventEmitter();
  private readonly channelRefs = new Map<string, number>();
  private sub: Redis | undefined;

  constructor(
    @Inject(COALESCING_REDIS_CLIENT) private readonly redis: Redis,
  ) {
    // Allow many concurrent waiters without Node.js printing a MaxListeners warning.
    this.emitter.setMaxListeners(0);
  }

  onModuleInit() {
    this.sub = this.redis.duplicate();
    this.sub.on('message', (channel: string, msg: string) =>
      this.emitter.emit(channel, msg),
    );
  }

  async onModuleDestroy() {
    // Quit the subscriber connection first, then the primary client.
    // Guard for the case where onModuleInit never ran (e.g. in tests).
    if (this.sub) await this.sub.quit();
    await this.redis.quit();
  }

  async coalesce<T>(key: string, fetcher: () => Promise<T>): Promise<T> {
    const lockKey = `lock:${key}`;
    const channel = `notify:${key}`;
    const resultKey = `result:${key}`;

    const acquired = await this.redis.set(lockKey, '1', 'EX', Math.ceil(LOCK_TTL_MS / 1000), 'NX');

    if (acquired === 'OK') {
      try {
        const result = await fetcher();
        // SET before PUBLISH so any subscriber that reads resultKey after
        // receiving 'done' is guaranteed to find the value.
        const successPayload = JSON.stringify({
          ok: true,
          data: result,
        });
        await this.redis.set(resultKey, successPayload, 'PX', LOCK_TTL_MS);
        await this.redis.publish(channel, 'done');
        return result;
      } catch (err) {
        // Notify waiters of the error so they fail fast with the same underlying
        // error instead of hanging until the timeout.
        try {
          const errorPayload = JSON.stringify({
            ok: false,
            error: (err as Error).message,
          });
          await this.redis.set(resultKey, errorPayload, 'PX', LOCK_TTL_MS);
          await this.redis.publish(channel, 'done');
        } catch {
          // Redis is down during error handling — waiters will time out. Nothing more we can do.
        }
        throw err;
      } finally {
        await this.redis.del(lockKey);
      }
    }

    return this.waitForNotification<T>(channel, resultKey);
  }

  private async waitForNotification<T>(
    channel: string,
    resultKey: string,
  ): Promise<T> {
    await this.subscribeChannel(channel);

    return new Promise<T>((resolve, reject) => {
      let settled = false;

      const finish = (fn: () => void | Promise<void>) => {
        if (settled) return;
        settled = true;
        this.emitter.removeListener(channel, handler);
        void this.unsubscribeChannel(channel);
        void Promise.resolve(fn()).catch((err: unknown) =>
          reject(err instanceof Error ? err : new Error(String(err))),
        );
      };

      const timeout = setTimeout(() => {
        finish(() =>
          reject(new Error(`Coalescing timed out on channel ${channel}`)),
        );
      }, LOCK_TTL_MS);

      const handler = async (msg: string) => {
        if (msg !== 'done') return;
        clearTimeout(timeout);
        finish(async () => {
          const raw = await this.redis.get(resultKey);
          if (raw) return this.settleFromPayload(raw, resolve, reject);
          reject(new Error(`Coalescing: no result found for ${resultKey}`));
        });
      };

      this.emitter.on(channel, handler);

      // Race condition fix: check if the lock-holder already published before
      // our subscribe() completed. If resultKey exists we settle immediately.
      void this.redis.get(resultKey).then((early: string | null) => {
        if (!early) return;
        clearTimeout(timeout);
        finish(() => this.settleFromPayload(early, resolve, reject));
      });
    });
  }

  private settleFromPayload<T>(
    raw: string,
    resolve: (value: T) => void,
    reject: (reason: Error) => void,
  ): void {
    const payload: CoalescingPayload<T> = JSON.parse(raw) as CoalescingPayload<T>;
    if (payload.ok === true) {
      resolve(payload.data);
    } else {
      reject(new Error(payload.error));
    }
  }

  private async subscribeChannel(channel: string): Promise<void> {
    if (!this.sub) throw new Error('RedisPubSubCoalescingService: onModuleInit has not run');
    const refs = (this.channelRefs.get(channel) ?? 0) + 1;
    this.channelRefs.set(channel, refs);
    if (refs === 1) await this.sub.subscribe(channel);
  }

  private async unsubscribeChannel(channel: string): Promise<void> {
    const refs = (this.channelRefs.get(channel) ?? 1) - 1;
    if (refs <= 0) {
      this.channelRefs.delete(channel);
      await this.sub?.unsubscribe(channel);
    } else {
      this.channelRefs.set(channel, refs);
    }
  }
}
