FROM node:22.15-alpine3.20 AS builder

RUN apk update && apk upgrade --no-cache
RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./
COPY backend/package.json backend/prisma.config.ts ./backend/
COPY backend/prisma ./backend/prisma

RUN pnpm install --filter backend... --frozen-lockfile --reporter=verbose

RUN cd backend && npx prisma generate --schema prisma/schema.prisma

COPY backend/src ./backend/src
COPY backend/tsconfig.json backend/tsconfig.build.json backend/nest-cli.json ./backend/

RUN pnpm --filter backend build:prod

FROM node:22.15-alpine3.20

RUN apk update && apk upgrade --no-cache
RUN npm install -g pnpm

WORKDIR /app

# 1. Copy workspace files to the root
COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./

# 2. Copy backend files (Added the destination './backend/' to the first line)
COPY backend/package.json backend/prisma.config.ts ./backend/
COPY backend/prisma ./backend/prisma

# 3. Install production dependencies
RUN pnpm install --prod --filter backend... --frozen-lockfile --reporter=verbose

# 4. Copy build artifacts from the builder stage
COPY --from=builder /app/backend/dist ./backend/dist
COPY --from=builder /app/backend/src/generated ./backend/src/generated

COPY backend/docker/docker-entrypoint.prod.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

WORKDIR /app/backend

ENTRYPOINT ["/entrypoint.sh"]
CMD ["node", "dist/main"]
